<?php include 'Header.php'?>

<h1>Project Euler Problem 2</h1>

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
<br>
<br>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
<br>
<br>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

<h2>Java</h2>

<?php include 'ProjectEuler2_java_src.php'?>

<h2>Console Output</h2>

<?php include 'ProjectEuler2_output.php'?>

<?php include 'Footer.php'?>