<?php include '../assets/includes/Header.php'?>

<h1>Project Euler Problem 12</h1>

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
<br>
<br>1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
<br>
<br>Let us list the factors of the first seven triangle numbers:
<br>
<br>1: 1
<br>3: 1,3
<br>6: 1,2,3,6
<br>10: 1,2,5,10
<br>15: 1,3,5,15
<br>21: 1,3,7,21
<br>28: 1,2,4,7,14,28
<br>We can see that 28 is the first triangle number to have over five divisors.
<br>
<br>What is the value of the first triangle number to have over five hundred divisors?

<h2>Java</h2>

<?php include 'ProjectEuler12_java_src.php'?>

<h2>Console Output</h2>

<?php include 'ProjectEuler12_output.php'?>

<?php include '../assets/includes/Footer.php'?>